### ISSUE TITLE
Clean way of dealing with State-Based BO

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#11]
I was thinking what would be better, if having the standard `BOptimizer` take 2 arguments in the optimize function (the State evaluation and the Reward evaluation), and providing a default argument that just takes the first element of the vector as reward (allowing thus to people who don't want to use State-Based optimization to keep using the `BOptimizer` in the same way that they are using it now); or keeping it the way it is (and checking that the return dimension of the EvalFunction is 1), and adding a new `StateBOptimizer`, that takes both arguments and provides no default.
Any opinions on this?

**Comment by costashatz** [comment]
Can you make your suggestions more clear? E.g. provide a simple example for each.

**Comment by fedeallocati** [comment]
Sure.
1st way, modify `BOptimizer`:
```
class BOptimizer {
        template <typename StateFunction, typename RewardFunction>
        void optimize(const StateFunction& seval, const RewardFunction& reval = reward::FirstElem(), bool reset = true)
        {
        ...
        }
}
```
Second way, keep `BOptimizer` the way it is now, and add a new optimizer:
```
class StateBOptimizer {
        template <typename StateFunction, typename RewardFunction>
        void optimize(const StateFunction& seval, const RewardFunction& reval, bool reset = true)
        {
        ...
        }
}
```

This is not a question of implementation, is a question about which API would be better/cleaner/nicer to provide and maintain.

**Comment by costashatz** [comment]
I like the first approach more. It seems better to have only one classes for BO. This `RewardFunction` would be passed to the acquisition function too?

**Comment by fedeallocati** [comment]
Yeah, actually I think it will be passed to the inner optimization, which will pass it to the acquisition function. I haven't implemented this, but more or less that was what I was thinking.

**Comment by costashatz** [comment]
I am okay with the first option. It's good to not have many classes for the same functionality/idea.

**Comment by Aneoshun** [comment]
Hi all, 

While I like your first proposition, I am wandering if this such specialization is actually needed. 
If you are using state-based BO, you mainly need to change the acquisition function and not the BOptimizer. 
So, from my point of view, it may be better to specialize the acquisition function via a template and a functor and to keep BOptimizer as it is. 

I think that the state-based BO is not the main feature of this lib and thus all the complexity added by this has to be restricted to elements that are only used with this feature.  The idea is to keep the rest of the lib as simple as possible. 

For example, we can imagine to have a intermediate acquisition_functor that takes 2 arguments (or templates) that define which acquisition function to use (UCB, EI, PI) and how convert the state into a performance (e.g., an euclidian distance toward a goal).

Do you see what I mean and what do you think about it?

(By the way, I really appreciate all you work about limbo)

Antoine CULLY
Phd-Candidate in Robotics and Artificial Intelligence
DGA-UPMC
Institut des Systèmes Intelligents et de Robotique
http://pages.isir.upmc.fr/~cully/website/

**Comment by fedeallocati** [comment]
Hi @Aneoshun,
I have thought about it, but the problem is that using it on that way enforces the "Goal" to be fixed, so you cannot optimize for one task, and then change it, keeping the state observations from the previous one, so the best I could think of to allow to have the flexibility of changing the Reward and keeping the State are the 2 alternatives that I proposed.
It seems like the first option is winning, so if there aren't any objections ( @jbmouret ? ), I will go in that way.

**Comment by Aneoshun** [comment]
Hum, I disagree with you. 
In fact the « reset » argument of the « optimize » method of BOptimizer is exactly here to enable this flexibly (and one of my experiments is in particular to switch between different goals).
if you want to change the goal after every iteration (which is useful for example to avoid obstacles), you just have to set the stopping criterion with 1 (or 0) IT.

Antoine CULLY
Phd-Candidate in Robotics and Artificial Intelligence
DGA-UPMC
Institut des Systèmes Intelligents et de Robotique
http://pages.isir.upmc.fr/~cully/website/

**Comment by fedeallocati** [comment]
I think I didn't understood you then. What I was meaning is that if we do something like:
`typedef StateAqui<UCB<Params, GP_bo_t>, Reward> Acqui_bo_t;`, that is, adding the Reward as a template parameter of the acquisition function type (or an intermediate acquisition), then it will stay fixed withen the same BOptimizer, because it's tied to the type of the acquision. Detailed example:
```
typedef boost::fusion::vector<stat::Acquisitions<Params>> Stat_t;
typedef boost::fusion::vector<stopping_criterion::MaxIterations<Params>> Stop_t;

typedef mean_functions::MeanData<Params> Mean_t;
typedef kernel_functions::SquaredExpARD<Params> Kernel_t;
typedef model::GPAuto<Params, Kernel_t, Mean_t> GP_bo_t;

typedef StateAqui<UCB<Params, GP_bo_t>, Reward1> Acqui_bo_t;

typedef inner_optimization::Cmaes<Params> InnerOpt_bo_t;

typedef BOptimizer<Params, model_fun<GP_bo_t>, init_fun<Init_t>, acq_fun<Acqui_bo_t>, inneropt_fun<InnerOpt_bo_t>, stat_fun<Stat_t>, stop_fun<Stop_t>> opt_bo_t;

opt_bo_t opt_bo;
opt_bo.optimize(StateEval());
```
In that example, there is no way to change the Reward function, because it's fixed to the type.
Instead, with what I'm proposing:
```
typedef boost::fusion::vector<stat::Acquisitions<Params>> Stat_t;
typedef boost::fusion::vector<stopping_criterion::MaxIterations<Params>> Stop_t;

typedef mean_functions::MeanData<Params> Mean_t;
typedef kernel_functions::SquaredExpARD<Params> Kernel_t;
typedef model::GPAuto<Params, Kernel_t, Mean_t> GP_bo_t;

typedef UCB<Params, GP_bo_t> Acqui_bo_t;

typedef inner_optimization::Cmaes<Params> InnerOpt_bo_t;

typedef BOptimizer<Params, model_fun<GP_bo_t>, init_fun<Init_t>, acq_fun<Acqui_bo_t>, inneropt_fun<InnerOpt_bo_t>, stat_fun<Stat_t>, stop_fun<Stop_t>> opt_bo_t;

opt_bo_t opt_bo;
opt_bo.optimize(StateEval(), Reward1()); // Run until completion
opt_bo.optimize(StateEval(), Reward2(), false); // Do not reset. to keep previous observations
```

You see what I meant?

**Comment by Aneoshun** [comment]
Ho, I see the difference. 

From my point of view, changing the goal is more like changing the variable/parameter than changing a whole function. 
I think that both of your examples can implement goal changes but in a different way.

With my proposition (which is well reflected by your example), the Reward functor can use a BO_DYN_PARAM, which defines the goal and which can be changed on the fly. 

I agree that your proposition allows more flexibility (because we can change the whole reward function). However, is it really useful? The idea behind state-based BO is that a goal is in fact a state in which we want to place the robot. Thus most of reward can be, theoretically, expressed as a state value and changing the reward scheme seems overkill. (What kind of changes is needed? changing the type of distance function? )

By the way, it is possible to have several reward functions and to switch between them with « my proposition » by using boost::fusion::vectors and a parameter that select which function to use. But again, I am not sure this is actually useful and this is way more complicated than your approach. 

So we need to answer two questions: 
- Is it useful to be able to change the reward function (and not only parameters)?
- Do we prefer a simple code for the standard mode or this additional flexibility?

At the end, I agree with both of the approaches, but I think this lib will mainly be used for the traditional BO algorithm, and because of that we have to make it as light and simple as possible specifically for this usage.

Antoine CULLY
Phd-Candidate in Robotics and Artificial Intelligence
DGA-UPMC
Institut des Systèmes Intelligents et de Robotique
http://pages.isir.upmc.fr/~cully/website/

**Comment by fedeallocati** [comment]
>So we need to answer two questions:
>- Is it useful to be able to change the reward function (and not only parameters)?

I think, as you said, it's much more flexible and also much more cleaner. With the approach I proposed, you can clearly see what's changing, and it's of course more general, one could still just change a parameter and don't make different types for the reward functions.

>- Do we prefer a simple code for the standard mode or this additional flexibility?

This was my main reason of asking this question. Adding a new `StateBOptimizer` seems reasonable if we want to have a simple code for the main use of the library, but also the "advanced" features for us to use on our experiments

**Comment by Aneoshun** [comment]
Le 16 oct. 2015 à 14:56, Federico Allocati <notifications@github.com> a écrit :

> So we need to answer two questions:
> 
> Is it useful to be able to change the reward function (and not only parameters)?
> I think, as you said, it's much more flexible and also much more cleaner. With the approach I proposed, you can clearly see what's changing, and it's of course more general, one could still just change a parameter and don't make different types for the reward functions.
> 
I completely agree with you, but this does not answer to the question: is it really useful to change the whole reward function on the fly? For example, we cannot do this with Sferes2 and we never needed such feature.
If we want to add this feature and thus to add some complexity in the standard mode, we need to be sure that we are doing it for a good reason and not for a feature that will not be used and which can be replaced by just changing a parameter. 

From my own experience, I never needed to change the whole reward function on the fly with this lib. Does someone imagine a situation in which this may be required? 

> Do we prefer a simple code for the standard mode or this additional flexibility?
> This was my main reason of asking this question. Adding a new StateBOptimizer seems reasonable if we want to have a simple code for the main use of the library, but also the "advanced" features for us to use on our experiments
> 
I am particularly opposed to this « second option » because it will probably require to duplicate code and this is a source of bugs (as said by Konstantinos).

**Comment by fedeallocati** [comment]
I'm sorry, I made an edit and didn't notified it.

The idea is that the "expensive" function is the StateEval, and that RewardEval just performs calculations with the state. I'm thinking it could be usefull in a more complex scenario, like trying to learn different "kind" of tasks, not just the same task with different targets.

I imagine a situation in the current robot I'm working on, which has an arm manipulator and a mobile base, so the learning process could alter between the tasks "move to target" and "grab target". Same thing could be applied to the iCub, "get close to target" and "interact with target". But I'm just thinking on the approach for robotics, probably other uses of the library doesn't benefit from this feature.

Also, I mentioned this to the other guys, but it's worth noting it here: This same approach of the reward function would be used to get the "best sample/observation", so you pass the Reward functor to those methods, and it's used as the criterion for the ordering (this now is fixed to compare according to the first element of the observation vector, which of course isn't good). An instant benefit of this is that you can see the performance of all your observations for all the different goals, (and we could make a stop criterion that looked at this and decides to stop is the task was already learned from observations for previous rewards).

When I proposed this improvement, JB and Konstantinos liked it, but I would like to know their opinion on your objections.

**Comment by costashatz** [comment]
I think I will go with Federico's side in this one, as it is not THAT complex and allows for greater flexibility (which I really like in generic libraries). In any case, if we see it is too complex, we can decline the pull request. It is not bad to explore things.

**Comment by jbmouret** [comment]
I still need to think about it but let's start with a few elements:
- changing things with BO_DYN_PARAMS is a hack that can be used for some research experiments, it should not be the "standard way" of doing something
- I agree with Antoine that it is better to keep the optimiser simple and not specialised for this state idea (that we may not keep at the end / may replace it by something else)
- It is also good to design our "building blocks" in an independent manner (e.g. I like Antoine's proposal `typedef StateAqui<UCB<Params, GP_bo_t>, Reward> Acqui_bo_t;` because it allows us to add a new functionality while keeping each component independent and 'clean')
- while flexibility has a cost (in term of complexity), a research framework has to help us to quickly try all our crazy ideas, therefore flexibility is a strength; in addition, having our own code instead of using something else (e.g. BayesOpt) is good because it allows us to taylor the code for the kind of ideas we are working on. Another way to say it is: we are not working on the perfect BO library, we are working on a framework that helps us to do our researches;
- overall, the main question/issue is "how often do we need to be able to switch between goals?" It is a difficult question for now!

... more later; I tend to agree with Federico (more flexibility) but I also like simple code with only the required abstractions.

**Comment by fedeallocati** [comment]
For the sake of simplicity, we can provide a default Reward function which just takes the first element of the Vector. 
I think it's worth implementing it and taking a look at it with concrete code. Will branch and make the pull request so we can discuss it.

**Comment by costashatz** [comment]
I am closing this issue and we will start a discussion again when @fedeallocati creates the pull request.
