### ISSUE TITLE
Switch to NLOpt by default (instead of CMA-ES)

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#146]
It seems that libcmaes is crashing on the last Ubuntu. We should switch to NLOpt by default (and check the examples).

**Comment by costashatz** [comment]
What's the status on this one? Is it really crushing because of latest Ubuntu version or linking/compilation issues of individuals?

**Comment by bpapaspyros** [comment]
As you know I did a fresh installation of Ubuntu 16.04 in a virtual machine and everything worked fine. I am not sure we need to switch to NLopt. Even if it was a bug in some earlier copy of Ubuntu 16.04 it seems it has been addressed.

**Comment by costashatz** [comment]
Do we have any news on this one?

**Comment by jbmouret** [comment]
Independently of this issue, I think I prefer to switch to NLOpt by default.

**Comment by costashatz** [comment]
> Independently of this issue, I think I prefer to switch to NLOpt by default.

It is ok for me. I will refactor it.. Which algorithm should we default to?

**Comment by jbmouret** [comment]
The same as BayesOpt?

**Comment by costashatz** [comment]
> The same as BayesOpt?

Since we are doing gradient-less optimization for the acquisition function, we should use the 'DIRECT' algorithm.

Although, as I see in BayesOpt (and I spoke with some BO experts in the summer school), maybe it's a good idea to also give the possibility of optimizing the acquisition function with gradients (for Expected Improvement for example it is easy to compute the gradients) -- which we don't give this possibility now.

**Comment by costashatz** [comment]
Fixed in #162...
