### ISSUE TITLE
The robotic task example for limbo.

### ISSUE THREAD

**Issue by langongjin** [resibots/limbo#284]
hi, @costashatz Thanks for your reply months ago. We talked about the issue about how to combine the limbo with the robot task. as following:

![image](https://user-images.githubusercontent.com/13703853/44617072-d04d8900-a85c-11e8-9107-3889941e4912.png)

would you like to update idea if you have any updating? I think that would be useful for the people who research on robot.

Thanks!

**Comment by langongjin** [comment]
Here is the link to the previous issue. https://github.com/resibots/limbo/issues/259

**Comment by langongjin** [comment]
Hi, my idea is that tuning the weights of the neural network controllers with Bayesian optimization. Because Bayesian optimization outperforms the EA in my test of searching function optimal. But I am not sure how it will work for the high dimensions of the neural network controllers of the robot. I am still set up the experiments and coding. Therefore, I have no more result to show you. Sometimes, I am a little doubt how the Bayesian optimization optimizes the neural network controller. This is why I want to see your example. Maybe your idea will make me more confidence and inspire me. Thanks!

**Comment by costashatz** [comment]
> Hi, my idea is that tuning the weights of the neural network controllers with Bayesian optimization. Because Bayesian optimization outperforms the EA in my test of searching function optimal. But I am not sure how it will work for the high dimensions of the neural network controllers of the robot. I am still set up the experiments and coding. Therefore, I have no more result to show you. Sometimes, I am a little doubt how the Bayesian optimization optimizes the neural network controller. This is why I want to see your example. Maybe your idea will make me more confidence and inspire me. Thanks!

Bayesian optimization (BO) is by definition not working very well in high-dimensions as is. It is very easy to see why, because basically we are creating a model of the objective function and the bigger dimensional it gets, we need exponentially more data to have accurate predictions (this is usually referred as curse-of-dimensionality). On the other hand, one can introduce priors to make BO tractable even in higher dimensions: this is usually inserted in the controller structure (i.e., not use a general purpose neural network, but a PID controller and fine-tune its parameters), but this is not the only type of prior knowledge.

You can have a look at the works of our lab where we try several ideas to make BO tractable for real robotic applications: https://www.resibots.eu/publications.html

In addition, you can have a look at our recent survey of policy search approaches (BO can be seen as a policy search approach) for learning robotic controllers in a handful of trials, where we talk about BO and other approaches for reducing the number of trials needed to learn on a physical robot: https://arxiv.org/abs/1807.02303

**Comment by langongjin** [comment]
This can not be better. You gave me a great summary. Thank you very much. I will keep updating my idea if I have the new result. Do you think we should keep this issue? or close this issue, and then start a new issue if we need to discuss?

**Comment by costashatz** [comment]
I am closing this issue and if you have something to add, you can re-open it or create a new one.. Glad that I helped!
